from typing import Protocol
from email.mime.multipart import MIMEMultipart

class SMTPClient(Protocol):
    """Protocol for SMTP client implementations"""
    async def connect(self) -> None: ...
    async def starttls(self) -> None: ...
    async def login(self, username: str, password: str) -> None: ...
    async def send_message(self, message: MIMEMultipart) -> None: ...
    async def quit(self) -> None: ...